// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;

namespace DSS2_SynchromodalityCapacityOptimisation.Services.salesForecasts.DataContracts
{
    public class ResponseDTO
    {
        public string Status
        {
            get;
            set;
        }
        public string Message
        {
            get;
            set;
        }
        public string Details
        {
            get;
            set;
        }
        public string Code
        {
            get;
            set;
        }
    }

    [KnownType(typeof(SalesForecastDetailsDTO))]
    public class SalesDTO
    {
        public DateTime? ForecastDate
        {
            get;
            set;
        }
        public int? Units
        {
            get;
            set;
        }
        public DSS2_SynchromodalityCapacityOptimisation.BO.Item Item
        {
            get;
            set;
        }
        public DSS2_SynchromodalityCapacityOptimisation.BO.Warehouse Warehouse
        {
            get;
            set;
        }
    }

    public class SalesForecastDetailsDTO : SalesDTO
    {
    }

    public class SalesForecastDTO
    {
        public int? ImportId
        {
            get;
            set;
        }
        public DateTime? ImportDate
        {
            get;
            set;
        }
        public System.Collections.Generic.List<SalesForecastDetailsDTO> SalesForecastDetails
        {
            get;
            set;
        }
    }


}