// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;
using System.ServiceModel.Channels;
using System.Security.Permissions;
using System.Security.Principal;
using NHibernate;
using System.ServiceModel.Activation;
using zAppDev.DotNet.Framework.Utilities;
using zAppDev.DotNet.Framework.Data.Domain;
using DSS2_SynchromodalityCapacityOptimisation.Services.salesForecasts.DataContracts;
using DSS2_SynchromodalityCapacityOptimisation.BO;
using AutoMapper;

namespace DSS2_SynchromodalityCapacityOptimisation.Services
{
    [AspNetCompatibilityRequirements(RequirementsMode = AspNetCompatibilityRequirementsMode.Required)]
    public class salesForecastsService : IsalesForecastsService
    {
        public ResponseDTO Import(System.Collections.Generic.List<SalesForecastDetailsDTO> _salesForecasts, string _RequestSourceIp, string _UserName)
        {
            InitializeMappers();
            try
            {
                var inputsalesForecasts = Mapper.Map<System.Collections.Generic.List<SalesForecastDetailsDTO>, System.Collections.Generic.List<DSS2_SynchromodalityCapacityOptimisation.BO.SalesForecastDetails>>(_salesForecasts);
                var _import = ImportImplementation(inputsalesForecasts);
                var result = Mapper.Map<DSS2_SynchromodalityCapacityOptimisation.BO.Response, ResponseDTO>(_import);
                return result;
            }
            catch (Exception @exception)
            {
                log4net.LogManager.GetLogger("salesForecasts Service").Error(@exception);
                throw;
            }
        }


        private void InitializeMappers()
        {
            Mapper.CreateMap<ResponseDTO, DSS2_SynchromodalityCapacityOptimisation.BO.Response>();
            Mapper.CreateMap<DSS2_SynchromodalityCapacityOptimisation.BO.Response, ResponseDTO>();
            Mapper.CreateMap<SalesDTO, DSS2_SynchromodalityCapacityOptimisation.BO.Sales>();
            Mapper.CreateMap<DSS2_SynchromodalityCapacityOptimisation.BO.Sales, SalesDTO>()
            .Include<DSS2_SynchromodalityCapacityOptimisation.BO.SalesForecastDetails, SalesForecastDetailsDTO>();
            Mapper.CreateMap<DSS2_SynchromodalityCapacityOptimisation.BO.SalesForecastDetails, SalesForecastDetailsDTO>();
            Mapper.CreateMap<SalesForecastDetailsDTO, DSS2_SynchromodalityCapacityOptimisation.BO.SalesForecastDetails>();
            Mapper.CreateMap<SalesForecastDTO, DSS2_SynchromodalityCapacityOptimisation.BO.SalesForecast>();
            Mapper.CreateMap<DSS2_SynchromodalityCapacityOptimisation.BO.SalesForecast, SalesForecastDTO>();
        }

        public static DSS2_SynchromodalityCapacityOptimisation.BO.Response ImportImplementation(System.Collections.Generic.List<DSS2_SynchromodalityCapacityOptimisation.BO.SalesForecastDetails> salesForecasts)
        {
            string message = "";
            DSS2_SynchromodalityCapacityOptimisation.BO.SalesForecast sForecast = new DSS2_SynchromodalityCapacityOptimisation.BO.SalesForecast();
            sForecast.ImportDate = DateTime.UtcNow;
            foreach (var salesForecast in salesForecasts ?? Enumerable.Empty<DSS2_SynchromodalityCapacityOptimisation.BO.SalesForecastDetails>())
            {
                zAppDev.DotNet.Framework.Utilities.DebugHelper.Log(zAppDev.DotNet.Framework.Utilities.DebugMessageType.Info, "API",  DSS2_SynchromodalityCapacityOptimisation.Hubs.EventsHub.RaiseDebugMessage, "Warehouse: " + (salesForecast?.Warehouse?.Code ?? ""));
                if ((salesForecast?.Item == null || salesForecast?.Warehouse == null))
                {
                    zAppDev.DotNet.Framework.Utilities.DebugHelper.Log(zAppDev.DotNet.Framework.Utilities.DebugMessageType.Info, "API",  DSS2_SynchromodalityCapacityOptimisation.Hubs.EventsHub.RaiseDebugMessage, "NULL");
                    message = message + (salesForecast?.Id ?? 0) + " ,";
                    continue;
                }
                var _var0 = salesForecast?.Item?.SKU;
                DSS2_SynchromodalityCapacityOptimisation.BO.Item existingItem = new DSS2_SynchromodalityCapacityOptimisation.DAL.Repository().GetAsQueryable<DSS2_SynchromodalityCapacityOptimisation.BO.Item>((s) => s.SKU == _var0)?.FirstOrDefault();
                var _var1 = salesForecast?.Warehouse?.Code;
                DSS2_SynchromodalityCapacityOptimisation.BO.Warehouse existingWarehouse = new DSS2_SynchromodalityCapacityOptimisation.DAL.Repository().GetAsQueryable<DSS2_SynchromodalityCapacityOptimisation.BO.Warehouse>((a) => a.Code == _var1)?.FirstOrDefault();
                if ((existingItem == null || existingWarehouse == null))
                {
                    message = message + (salesForecast?.Id ?? 0) + " ,";
                    continue;
                }
                DSS2_SynchromodalityCapacityOptimisation.BO.SalesForecastDetails newSalesForecast = new DSS2_SynchromodalityCapacityOptimisation.BO.SalesForecastDetails();
                newSalesForecast.Warehouse = existingWarehouse;
                newSalesForecast.Item = existingItem;
                newSalesForecast.ForecastDate = (salesForecast?.ForecastDate ?? System.Data.SqlTypes.SqlDateTime.MinValue.Value);
                newSalesForecast.Units = (salesForecast?.Units ?? 0);
                newSalesForecast.SalesForecast = sForecast;
                new DSS2_SynchromodalityCapacityOptimisation.DAL.Repository().Save<DSS2_SynchromodalityCapacityOptimisation.BO.SalesForecastDetails>(newSalesForecast);
            }
            new DSS2_SynchromodalityCapacityOptimisation.DAL.Repository().Save<DSS2_SynchromodalityCapacityOptimisation.BO.SalesForecast>(sForecast);
            if (((((message == null || message == "")) == false)))
            {
                zAppDev.DotNet.Framework.Utilities.DebugHelper.Log(zAppDev.DotNet.Framework.Utilities.DebugMessageType.Warning, "API",  DSS2_SynchromodalityCapacityOptimisation.Hubs.EventsHub.RaiseDebugMessage, "Error message: " + message);
                return DSS2_SynchromodalityCapacityOptimisation.BO.ResponseExtensions.GenerateResponse("Failed", "Failed to import the entries with Ids " + message, "", "-1");
            }
            return DSS2_SynchromodalityCapacityOptimisation.BO.ResponseExtensions.GenerateResponse("Succeed", "All entries imported successfully.", "", "1");
        }


    }
}