// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).
using System;
using System.Runtime.Serialization;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Collections;
using System.ComponentModel.DataAnnotations;
using System.Linq.Expressions;
using zAppDev.DotNet.Framework.Linq;
using zAppDev.DotNet.Framework.Data.Domain;
using zAppDev.DotNet.Framework.Workflow;
using zAppDev.DotNet.Framework.Identity.Model;

namespace DSS2_SynchromodalityCapacityOptimisation.BO
{
    /// <summary>
    /// The tblReceivedEvent class
    ///
    /// </summary>
    [Serializable]
    [DataContract]
    public class tblReceivedEvent : IDomainModelClass
    {
        #region tblReceivedEvent's Fields

        protected Guid _transientId= Guid.NewGuid();
        public virtual Guid TransientId
        {
            get
            {
                return _transientId;
            }
            set
            {
                _transientId = value;
            }
        }
        [DataMember(Name="ReceivedEventID")]
        protected long? receivedEventID = 0L;
        [DataMember(Name="EntryDate")]
        protected DateTime? entryDate;
        [DataMember(Name="date")]
        protected string _date;
        [DataMember(Name="event_type")]
        protected string _event_type;
        [DataMember(Name="event_value_type")]
        protected string _event_value_type;
        [DataMember(Name="event_value")]
        protected string _event_value;
        [DataMember(Name="LastUpdated")]
        protected DateTime? lastUpdated;
        [DataMember(Name="VersionTimestamp")]
        protected byte[] versionTimestamp;

        #endregion
        #region tblReceivedEvent's Properties
/// <summary>
/// The ReceivedEventID property
///
/// </summary>
///
        [Key]
        public virtual long? ReceivedEventID
        {
            get
            {
                return receivedEventID;
            }
            set
            {
                receivedEventID = value;
            }
        }
/// <summary>
/// The EntryDate property
///
/// </summary>
///
        public virtual DateTime? EntryDate
        {
            get
            {
                return entryDate;
            }
            set
            {
                entryDate = value;
            }
        }
/// <summary>
/// The date property
///
/// </summary>
///
        public virtual string date
        {
            get
            {
                return _date;
            }
            set
            {
                _date = value;
            }
        }
/// <summary>
/// The event_type property
///
/// </summary>
///
        public virtual string event_type
        {
            get
            {
                return _event_type;
            }
            set
            {
                _event_type = value;
            }
        }
/// <summary>
/// The event_value_type property
///
/// </summary>
///
        public virtual string event_value_type
        {
            get
            {
                return _event_value_type;
            }
            set
            {
                _event_value_type = value;
            }
        }
/// <summary>
/// The event_value property
///
/// </summary>
///
        public virtual string event_value
        {
            get
            {
                return _event_value;
            }
            set
            {
                _event_value = value;
            }
        }
/// <summary>
/// The LastUpdated property
///
/// </summary>
///
        public virtual DateTime? LastUpdated
        {
            get
            {
                return lastUpdated;
            }
            set
            {
                lastUpdated = value;
            }
        }
/// <summary>
/// The VersionTimestamp property
///Provides concurrency control for the class
/// </summary>
///
        public virtual byte[] VersionTimestamp
        {
            get
            {
                return versionTimestamp;
            }
            set
            {
                versionTimestamp = value;
            }
        }
        #endregion
        #region tblReceivedEvent's Participant Properties
        [DataMember(Name="tblReceivedPlannedTransport")]
        protected tblReceivedPlannedTransport _tblReceivedPlannedTransport;
        public virtual tblReceivedPlannedTransport tblReceivedPlannedTransport
        {
            get
            {
                return _tblReceivedPlannedTransport;
            }
            set
            {
                if(Equals(_tblReceivedPlannedTransport, value)) return;
                var __oldValue = _tblReceivedPlannedTransport;
                if (value != null)
                {
                    _tblReceivedPlannedTransport = value;
                }
                else
                {
                    if (_tblReceivedPlannedTransport != null)
                    {
                        _tblReceivedPlannedTransport = null;
                    }
                }
            }
        }
        #endregion
        #region Constructors
/// <summary>
/// Public constructors of the tblReceivedEvent class
/// </summary>
/// <returns>New tblReceivedEvent object</returns>
/// <remarks></remarks>
        public tblReceivedEvent() {}
        #endregion
        #region Methods

        public virtual List<string> _Validate(bool throwException = true)
        {
            var __errors = new List<string>();
            if (ReceivedEventID == null)
            {
                __errors.Add("Property 'ReceivedEventID' is required.");
            }
            if (date != null && date.Length > 100)
            {
                __errors.Add("Length of property 'date' cannot be greater than 100.");
            }
            if (event_type != null && event_type.Length > 100)
            {
                __errors.Add("Length of property 'event_type' cannot be greater than 100.");
            }
            if (event_value_type != null && event_value_type.Length > 100)
            {
                __errors.Add("Length of property 'event_value_type' cannot be greater than 100.");
            }
            if (event_value != null && event_value.Length > 100)
            {
                __errors.Add("Length of property 'event_value' cannot be greater than 100.");
            }
            if (throwException && __errors.Any())
            {
                throw new zAppDev.DotNet.Framework.Exceptions.BusinessException("An instance of TypeClass 'tblReceivedEvent' has validation errors:\r\n\r\n" + string.Join("\r\n", __errors));
            }
            return __errors;
        }

        public virtual int _GetUniqueIdentifier()
        {
            var hashCode = 399326290;
            hashCode = hashCode * -1521134295 + (ReceivedEventID?.GetHashCode() ?? 0);
            hashCode = hashCode * -1521134295 + (EntryDate?.GetHashCode() ?? 0);
            hashCode = hashCode * -1521134295 + (date?.GetHashCode() ?? 0);
            hashCode = hashCode * -1521134295 + (event_type?.GetHashCode() ?? 0);
            hashCode = hashCode * -1521134295 + (event_value_type?.GetHashCode() ?? 0);
            hashCode = hashCode * -1521134295 + (event_value?.GetHashCode() ?? 0);
            hashCode = hashCode * -1521134295 + (LastUpdated?.GetHashCode() ?? 0);
            return hashCode;
        }






/// <summary>
/// Copies the current object to a new instance
/// </summary>
/// <param name="deep">Copy members that refer to objects external to this class (not dependent)</param>
/// <param name="copiedObjects">Objects that should be reused</param>
/// <param name="asNew">Copy the current object as a new one, ready to be persisted, along all its members.</param>
/// <param name="reuseNestedObjects">If asNew is true, this flag if set, forces the reuse of all external objects.</param>
/// <param name="copy">Optional - An existing [tblReceivedEvent] instance to use as the destination.</param>
/// <returns>A copy of the object</returns>
        public virtual tblReceivedEvent Copy(bool deep=false, Hashtable copiedObjects=null, bool asNew=false, bool reuseNestedObjects = false, tblReceivedEvent copy = null)
        {
            if(copiedObjects == null)
            {
                copiedObjects = new Hashtable();
            }
            if (copy == null && copiedObjects.Contains(this))
                return (tblReceivedEvent)copiedObjects[this];
            copy = copy ?? new tblReceivedEvent();
            if (!asNew)
            {
                copy.TransientId = this.TransientId;
                copy.ReceivedEventID = this.ReceivedEventID;
            }
            copy.EntryDate = this.EntryDate;
            copy.date = this.date;
            copy.event_type = this.event_type;
            copy.event_value_type = this.event_value_type;
            copy.event_value = this.event_value;
            copy.LastUpdated = this.LastUpdated;
            if (!copiedObjects.Contains(this))
            {
                copiedObjects.Add(this, copy);
            }
            if(deep && this._tblReceivedPlannedTransport != null)
            {
                if (!copiedObjects.Contains(this._tblReceivedPlannedTransport))
                {
                    if (asNew && reuseNestedObjects)
                        copy.tblReceivedPlannedTransport = this.tblReceivedPlannedTransport;
                    else if (asNew)
                        copy.tblReceivedPlannedTransport = this.tblReceivedPlannedTransport.Copy(deep, copiedObjects, true);
                    else
                        copy._tblReceivedPlannedTransport = this._tblReceivedPlannedTransport.Copy(deep, copiedObjects, false);
                }
                else
                {
                    if (asNew)
                        copy.tblReceivedPlannedTransport = (tblReceivedPlannedTransport)copiedObjects[this.tblReceivedPlannedTransport];
                    else
                        copy._tblReceivedPlannedTransport = (tblReceivedPlannedTransport)copiedObjects[this.tblReceivedPlannedTransport];
                }
            }
            return copy;
        }

        public override bool Equals(object obj)
        {
            var compareTo = obj as tblReceivedEvent;
            if (ReferenceEquals(this, compareTo))
            {
                return true;
            }
            if (compareTo == null || !this.GetType().Equals(compareTo.GetTypeUnproxied()))
            {
                return false;
            }
            if (this.HasSameNonDefaultIdAs(compareTo))
            {
                return true;
            }
            // Since the Ids aren't the same, both of them must be transient to
            // compare domain signatures; because if one is transient and the
            // other is a persisted entity, then they cannot be the same object.
            return this.IsTransient() && compareTo.IsTransient() && (base.Equals(compareTo) || this.TransientId.Equals(compareTo.TransientId));
        }

// Maintain equality operator semantics for entities.
        public static bool operator ==(tblReceivedEvent x, tblReceivedEvent y)
        {
            // By default, == and Equals compares references. In order to
            // maintain these semantics with entities, we need to compare by
            // identity value. The Equals(x, y) override is used to guard
            // against null values; it then calls EntityEquals().
            return Equals(x, y);
        }

// Maintain inequality operator semantics for entities.
        public static bool operator !=(tblReceivedEvent x, tblReceivedEvent y)
        {
            return !(x == y);
        }

        private PropertyInfo __propertyKeyCache;
        public virtual PropertyInfo GetPrimaryKey()
        {
            if (__propertyKeyCache == null)
            {
                __propertyKeyCache = this.GetType().GetProperty("ReceivedEventID");
            }
            return __propertyKeyCache;
        }


/// <summary>
///     To help ensure hashcode uniqueness, a carefully selected random number multiplier
///     is used within the calculation.  Goodrich and Tamassia's Data Structures and
///     Algorithms in Java asserts that 31, 33, 37, 39 and 41 will produce the fewest number
///     of collissions.  See http://computinglife.wordpress.com/2008/11/20/why-do-hash-functions-use-prime-numbers/
///     for more information.
/// </summary>
        private const int HashMultiplier = 31;
        private int? cachedHashcode;

        public override int GetHashCode()
        {
            if (this.cachedHashcode.HasValue)
            {
                return this.cachedHashcode.Value;
            }
            if (this.IsTransient())
            {
                //this.cachedHashcode = base.GetHashCode();
                return this.TransientId.GetHashCode(); //don't cache because this won't stay transient forever
            }
            else
            {
                unchecked
                {
                    // It's possible for two objects to return the same hash code based on
                    // identically valued properties, even if they're of two different types,
                    // so we include the object's type in the hash calculation
                    var hashCode = this.GetType().GetHashCode();
                    this.cachedHashcode = (hashCode * HashMultiplier) ^ this.ReceivedEventID.GetHashCode();
                }
            }
            return this.cachedHashcode.Value;
        }

/// <summary>
///     Transient objects are not associated with an item already in storage.  For instance,
///     a Customer is transient if its Id is 0.  It's virtual to allow NHibernate-backed
///     objects to be lazily loaded.
/// </summary>
        public virtual bool IsTransient()
        {
            return this.ReceivedEventID == default(long) || this.ReceivedEventID.Equals(default(long));
        }

/// <summary>
///     When NHibernate proxies objects, it masks the type of the actual entity object.
///     This wrapper burrows into the proxied object to get its actual type.
///
///     Although this assumes NHibernate is being used, it doesn't require any NHibernate
///     related dependencies and has no bad side effects if NHibernate isn't being used.
///
///     Related discussion is at http://groups.google.com/group/sharp-architecture/browse_thread/thread/ddd05f9baede023a ...thanks Jay Oliver!
/// </summary>
        protected virtual System.Type GetTypeUnproxied()
        {
            return this.GetType();
        }

/// <summary>
///     Returns true if self and the provided entity have the same Id values
///     and the Ids are not of the default Id value
/// </summary>
        protected bool HasSameNonDefaultIdAs(tblReceivedEvent compareTo)
        {
            return !this.IsTransient() && !compareTo.IsTransient() && this.ReceivedEventID.Equals(compareTo.ReceivedEventID);
        }

        #endregion


    }
}
