// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).

using zAppDev.DotNet.Framework.Services;
using System;
using System.IO;
using System.Text;
using System.Linq;
using System.Xml.Serialization;
using System.Collections.Generic;

namespace DSS2_SynchromodalityCapacityOptimisation.BLL.ExternalRestServices
{
    public class LocalPubSubRestService
    {
        public static string BaseUrl
        {
            get
            {
                var baseUrl = System.Configuration.ConfigurationManager.AppSettings["externalapis:LocalPubSub:baseurl"];
                if (string.IsNullOrWhiteSpace(baseUrl))
                {
                    baseUrl = "http://selis-gw.cslab.ece.ntua.gr:20003/";
                }
                if (!string.IsNullOrWhiteSpace(baseUrl) && !baseUrl.EndsWith("/"))
                {
                    baseUrl += "/";
                }
                return baseUrl;
            }
        }

        public static decimal? Publish(DSS2_SynchromodalityCapacityOptimisation.ExternalStructs.LocalPubSub.Publication publication)
        {
            System.Func<string> getUrl = () =>
            {
                System.Threading.Thread.CurrentThread.CurrentCulture = System.Globalization.CultureInfo.InvariantCulture;
                return "publish";
            };
            var _operationRelativeUrl = getUrl.Invoke().Trim();
            if (_operationRelativeUrl?.StartsWith("/") == true && BaseUrl?.EndsWith("/") == true)
            {
                _operationRelativeUrl = _operationRelativeUrl.TrimStart('/');
            }
            var _targetUrl = BaseUrl + _operationRelativeUrl;
            var _options = new RestServiceConsumptionOptions
            {
                Url = _targetUrl,
                Verb = RestHTTPVerb.POST,
                ExtraHeaderData = new System.Collections.Generic.Dictionary<string, string>(StringComparer.OrdinalIgnoreCase) {   },
                LogAccess = false,
                IsCachingEnabled = false,
                ApiName = "LocalPubSub",
                Operation = "Publish",
                PostType = PostType.JSON,
                Data = publication, FormData = new Dictionary<string, object> {{"publication",publication}}
            };
            Func<ServiceConsumptionContainer, decimal?> _invocation = (_httpResponse) =>
            {
                var _returnedItem = RestServiceConsumer.Consume<decimal?>(_options, _httpResponse);
                return zAppDev.DotNet.Framework.Utilities.Common.SafeCast<decimal?>(_returnedItem);
            };
            var _consumer = new ServiceConsumer<decimal?>(_invocation);
            return _consumer.Invoke(_options);
        }
        public static DSS2_SynchromodalityCapacityOptimisation.ExternalStructs.LocalPubSub.SubscribeResult Subscribe(DSS2_SynchromodalityCapacityOptimisation.ExternalStructs.LocalPubSub.SubRoot subRules)
        {
            System.Func<string> getUrl = () =>
            {
                System.Threading.Thread.CurrentThread.CurrentCulture = System.Globalization.CultureInfo.InvariantCulture;
                return "subscribe";
            };
            var _operationRelativeUrl = getUrl.Invoke().Trim();
            if (_operationRelativeUrl?.StartsWith("/") == true && BaseUrl?.EndsWith("/") == true)
            {
                _operationRelativeUrl = _operationRelativeUrl.TrimStart('/');
            }
            var _targetUrl = BaseUrl + _operationRelativeUrl;
            var _options = new RestServiceConsumptionOptions
            {
                Url = _targetUrl,
                Verb = RestHTTPVerb.POST,
                ExtraHeaderData = new System.Collections.Generic.Dictionary<string, string>(StringComparer.OrdinalIgnoreCase) {   },
                LogAccess = false,
                IsCachingEnabled = false,
                ApiName = "LocalPubSub",
                Operation = "Subscribe",
                PostType = PostType.JSON,
                Data = subRules, FormData = new Dictionary<string, object> {{"subRules",subRules}}
            };
            Func<ServiceConsumptionContainer, DSS2_SynchromodalityCapacityOptimisation.ExternalStructs.LocalPubSub.SubscribeResult> _invocation = (_httpResponse) =>
            {
                var _returnedItem = RestServiceConsumer.Consume<DSS2_SynchromodalityCapacityOptimisation.ExternalStructs.LocalPubSub.SubscribeResult>(_options, _httpResponse);
                return zAppDev.DotNet.Framework.Utilities.Common.SafeCast<DSS2_SynchromodalityCapacityOptimisation.ExternalStructs.LocalPubSub.SubscribeResult>(_returnedItem);
            };
            var _consumer = new ServiceConsumer<DSS2_SynchromodalityCapacityOptimisation.ExternalStructs.LocalPubSub.SubscribeResult>(_invocation);
            return _consumer.Invoke(_options);
        }

    }
}