// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).

using System;
using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;
using FluentNHibernate.Testing;
using DSS2_SynchromodalityCapacityOptimisation.BO;
using DSS2_SynchromodalityCapacityOptimisation.BoTesting.Tests.Common;
using DSS2_SynchromodalityCapacityOptimisation.DAL;

namespace DSS2_SynchromodalityCapacityOptimisation.BoTesting.Tests
{
    /// <summary>
    ///This is a test class for DistanceCostsTest and is intended
    ///to contain all DistanceCostsTest NUnit Tests
    ///</summary>
    [TestFixture]
    [Description("DistanceCosts Repository Tests")]
    [Category("DistanceCosts Repository Tests")]
    internal class DistanceCostsTests : NHibernateFixture
    {
        /// <summary>
        ///A test for testing the persistence of an object from Db
        ///</summary>
        [Test]
        [Description("This tests the persistence of `DistanceCosts`")]
        [Order(0)]
        public void DistanceCosts_persistence_test()
        {
            DateTime now = DateTime.Now;
            // Get datetime without milliseconds
            now = new DateTime(now.Ticks - (now.Ticks % TimeSpan.TicksPerSecond), now.Kind);
            var _vehiculebo_propulsiontypecost_distancecosts = new DSS2_SynchromodalityCapacityOptimisation.BO.PropulsionTypeCost
            {
                Cost = 222222.22M,
                AverageConsumption = 222222.22M,
                Percentage = 222222.22M,
            };
            var _vehiculebo_propulsiontypecost_distancecosts2 = new DSS2_SynchromodalityCapacityOptimisation.BO.PropulsionTypeCost
            {
                Cost = 222222.22M,
                AverageConsumption = 222222.22M,
                Percentage = 222222.22M,
            };
            new PersistenceSpecification<DSS2_SynchromodalityCapacityOptimisation.BO.DistanceCosts>(Session)
            .CheckProperty(p => p.TotalDistanceDriven, 222222.22M)
            .CheckProperty(p => p.TotalDistanceService, 222222.22M)
            .CheckProperty(p => p.OilCost, 222222.22M)
            .CheckProperty(p => p.OilConsumption, 222222.22M)
            .CheckProperty(p => p.TireCost, 222222.22M)
            .CheckProperty(p => p.YearlyReparationCost, 222222.22M)
            .CheckProperty(p => p.Cost, 222222.22M)
            .CheckProperty(p => p.TireConsumption, 222222.22M)
            .CheckBag(p => p.PropulsionTypeCost, (new List<DSS2_SynchromodalityCapacityOptimisation.BO.PropulsionTypeCost>
            {
                _vehiculebo_propulsiontypecost_distancecosts,
                _vehiculebo_propulsiontypecost_distancecosts2
            }))
            .VerifyTheMappings();
        }

        /// <summary>
        ///A test for testing the filtering of an object from Db
        ///</summary>
        [Test]
        [Description("This tests the filtering of `DistanceCosts`")]
        [Order(1)]
        public void DistanceCosts_filtering_test()
        {
            DateTime now = DateTime.Now;
            // Get datetime without milliseconds
            now = new DateTime(now.Ticks - (now.Ticks % TimeSpan.TicksPerSecond), now.Kind);
            var repo = new Repository(Session);
            List<DSS2_SynchromodalityCapacityOptimisation.BO.DistanceCosts> results = null;
            Assert.DoesNotThrow(() =>
            {
                results = repo.GetAsQueryable<DSS2_SynchromodalityCapacityOptimisation.BO.DistanceCosts>(
                              a => true
                              && (a.TotalDistanceDriven + 123 > 0)
                              && (a.TotalDistanceService + 123 > 0)
                              && (a.OilCost + 123 > 0)
                              && (a.OilConsumption + 123 > 0)
                              && (a.TireCost + 123 > 0)
                              && (a.YearlyReparationCost + 123 > 0)
                              && (a.Cost + 123 > 0)
                              && (a.TireConsumption + 123 > 0)
                              && a.PropulsionTypeCost.Any()
                              ,
                              cacheQuery: true)
                          .OrderBy(a => a)
                          .Skip(0)
                          .Take(3)
                          .ToList();
            });
            Assert.AreNotEqual(null, results);
        }
    }
}