// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).

using System;
using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;
using FluentNHibernate.Testing;
using DSS2_SynchromodalityCapacityOptimisation.BO;
using DSS2_SynchromodalityCapacityOptimisation.BoTesting.Tests.Common;
using DSS2_SynchromodalityCapacityOptimisation.DAL;

namespace DSS2_SynchromodalityCapacityOptimisation.BoTesting.Tests
{
    /// <summary>
    ///This is a test class for TransportUnCapTest and is intended
    ///to contain all TransportUnCapTest NUnit Tests
    ///</summary>
    [TestFixture]
    [Description("TransportUnCap Repository Tests")]
    [Category("TransportUnCap Repository Tests")]
    internal class TransportUnCapTests : NHibernateFixture
    {
        /// <summary>
        ///A test for testing the persistence of an object from Db
        ///</summary>
        [Test]
        [Description("This tests the persistence of `TransportUnCap`")]
        [Order(0)]
        public void TransportUnCap_persistence_test()
        {
            DateTime now = DateTime.Now;
            // Get datetime without milliseconds
            now = new DateTime(now.Ticks - (now.Ticks % TimeSpan.TicksPerSecond), now.Kind);
            var _transportuncap_warehouse_transportuncap = new DSS2_SynchromodalityCapacityOptimisation.BO.Warehouse
            {
                Code = "Warehouse_Code",
                Description = "Warehouse_Description",
                FlowType = "Warehouse_FlowType",
                Title = "Warehouse_Title",
                Address = "Warehouse_Address",
                Telephone = "Warehouse_Telephone",
            };
            new PersistenceSpecification<DSS2_SynchromodalityCapacityOptimisation.BO.TransportUnCap>(Session)
            .CheckProperty(p => p.UOP, "TransportUnCap_UOP")
            .CheckProperty(p => p.PercRound, 2222222222.22222M)
            .CheckProperty(p => p.Tuc1, 2222222222.22222M)
            .CheckProperty(p => p.SplitOcInd, "TransportUnCap_SplitOcInd")
            .CheckProperty(p => p.Status, "TransportUnCap_Status")
            .CheckReference(p => p.Warehouse, _transportuncap_warehouse_transportuncap)
            .VerifyTheMappings();
        }

        /// <summary>
        ///A test for testing the filtering of an object from Db
        ///</summary>
        [Test]
        [Description("This tests the filtering of `TransportUnCap`")]
        [Order(1)]
        public void TransportUnCap_filtering_test()
        {
            DateTime now = DateTime.Now;
            // Get datetime without milliseconds
            now = new DateTime(now.Ticks - (now.Ticks % TimeSpan.TicksPerSecond), now.Kind);
            var repo = new Repository(Session);
            List<DSS2_SynchromodalityCapacityOptimisation.BO.TransportUnCap> results = null;
            Assert.DoesNotThrow(() =>
            {
                results = repo.GetAsQueryable<DSS2_SynchromodalityCapacityOptimisation.BO.TransportUnCap>(
                              a => true
                              && (a.UOP != string.Empty && a.UOP != null)
                              && (a.PercRound + 123 > 0)
                              && (a.Tuc1 + 123 > 0)
                              && (a.SplitOcInd != string.Empty && a.SplitOcInd != null)
                              && (a.Status != string.Empty && a.Status != null)
                              && a.Warehouse != null
                              ,
                              cacheQuery: true)
                          .OrderBy(a => a)
                          .Skip(0)
                          .Take(3)
                          .ToList();
            });
            Assert.AreNotEqual(null, results);
        }
    }
}