// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).
var DSS2_SynchromodalityCapacityOptimisation;
(function (DSS2_SynchromodalityCapacityOptimisation) {
    var Services;
    (function (Services) {
        /**
         * Client for 'exportItems' Service
         */
        var exportItemsServiceClient = (function () {
            function exportItemsServiceClient() {
            }
            /**
            *
            */
            exportItemsServiceClient.Export = function () {
                var _data = { params: {} };
                return axios.get(window._context.siteRoot + exportItemsServiceClient.baseUrl + "Export", _data);
            };
            return exportItemsServiceClient;
        }());
        /**
         * Base url for 'exportItems' Service
         */
        exportItemsServiceClient.baseUrl = "/api/exportItems/";
        Services.exportItemsServiceClient = exportItemsServiceClient;
    })(Services = DSS2_SynchromodalityCapacityOptimisation.Services || (DSS2_SynchromodalityCapacityOptimisation.Services = {}));
})(DSS2_SynchromodalityCapacityOptimisation || (DSS2_SynchromodalityCapacityOptimisation = {}));
// Create service shortcut
if (window.$api == null) {
    window.$api = {};
}
window.$api.exportItems = DSS2_SynchromodalityCapacityOptimisation.Services.exportItemsServiceClient;
